### ISSUE TITLE
Name and picture aren't always available, it causes a failure to auth 

### ISSUE THREAD

**Issue by armyofgnomes** [trchopan/firebase-auth#1]
I'm not sure if this is just for users who signed up through email or if it's something Firebase changed for everyone, but if name and picture aren't available for a user, it causes the authentication process to fail.

**Comment by trchopan** [comment]
Hi @armyofgnomes ,
Sorry for late response and thank you for creating this issue.
I will check it out soon. 🙇‍♂️

**Comment by trchopan** [comment]
I merged. Thanks again and good day to you!

**Comment by armyofgnomes** [comment]
No worries, thanks for merging! Hope you have a good day too!
