### ISSUE TITLE
Support Session Cookies?

### ISSUE THREAD

**Issue by benwr** [trchopan/firebase-auth#10]
Hi! I'm working on a multi-page app using firebase auth. I'd really like to use this crate to manage authentication, but it's not possible to include the required header with every page load. Firebase [does make it possible to use session cookies](https://firebase.google.com/docs/auth/admin/manage-cookies) for similar use-cases. Is this within scope for this library?

**Comment by trchopan** [comment]
Hi benwr, Thank you for open the ticket. Currently I not yet think of all the usecases of this library. I will spend something researching the feature that you suggested.

**Comment by trchopan** [comment]
Hi @benwr long time no reply this thread.
I'm aware that sessions keeping is the job of the application not this library.
I would like to close t his request for now. Thank you for asking it.
