### ISSUE TITLE
Support other claims info

### ISSUE THREAD

**Issue by simpleblack** [trchopan/firebase-auth#17]
hello.
I am using firebase and hasura together.
I'm trying to create an API server with rust, and I found the firebase_auth rust.
However, I cannot get it from claims as shown below.
The reason is that the struct FirebaseUser struct is fixed.

https://github.com/trchopan/firebase-auth/blob/main/firebase-auth/src/structs.rs#L30C1-L30C26
To solve the problem, claims need to be used flexibly. What method should I use?

```
{
    'https://hasura.io/jwt/claims': {
        'x-hasura-default-role': 'user',
        'x-hasura-allowed-roles': ['user'],
        'x-hasura-user-id': user_id
    },
    'iss': 'https://securetoekn.google.com/example-app',
    'aud': 'example-app',
    'auth_time: 0000000,
    'user_id: firebase_auth_user_id,
    ....
};
```

**Comment by trchopan** [comment]
@simpleblack Hi.
Thank you for mention it. I have this feature on my development list. I will implement it in a few days.
Best,

**Comment by trchopan** [comment]
@simpleblack I have example for custom claims like so. You may want to try it out.
https://github.com/trchopan/firebase-auth/blob/main/examples/actix-custom-claims/src/main.rs

**Comment by simpleblack** [comment]
@trchopan 
Thank you
