### ISSUE TITLE
Public keys don't update

### ISSUE THREAD

**Issue by a-pechenyi** [trchopan/firebase-auth#25]
When the app runs for an extended period, the public keys fail to update, resulting in a `VerificationError::NotfoundMatchKid`. This issue seems to occur specifically with the `axum` integration.

The root cause lies in the `FirebaseAuthState`. During its cloning process, it also clones `FirebaseAuth`. However, when one of these clones is dropped, the `Drop` handler of `FirebaseAuth` cancels the future spawned in `start_key_update`.

I am willing to address this issue, but it will necessitate changes that are not backward compatible. Specifically, I propose modifying `FirebaseAuthState` to contain `Arc<FirebaseAuth>` instead of `FirebaseAuth`, and removing the `FromRef<FirebaseAuthState> for FirebaseAuth` implementation.

Additionally, another issue arises within the `start_key_update` function. Based on the logs, it appears that there should be a `loop` statement somewhere, but it's missing. Upon reviewing a commit from [8 months ago](https://github.com/trchopan/firebase-auth/commit/a75a8e362b92d5fff516de2ad82fb67899855ca7), it seems that the `loop` was accidentally removed. It was present before.

**Comment by trchopan** [comment]
Merged https://github.com/trchopan/firebase-auth/pull/26
